
app:
  doppler:
    url: https://api.doppler.com/
    token: ${DOPPLER-TOKEN}
    projectName: ${DOPPLER_PROJECT_NAME}
    configurationName: ${DOPPLER_CONFIG_NAME}
  client:
    alias-name: na-studios
    server-private-key: classpath:cert/server/mainserver.key
    server-pubic-key: classpath:cert/server/server.pem
    client-private-key: classpath:cert/client/client.key
    client-public-key: classpath:cert/client/client.pem
    password: qwerty
    key-store-file-name: store.jks
    client-name: NANA



#logging:
#  level:
#    root: trace

spring:
  application:
    name: "MTLS - Client"
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost:5554}/${DB_NAME:mtlsDB}"
    hikari:
      username: postgres
      password: postgres
      schema: public
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.hikari.username}
    password: ${spring.datasource.hikari.password}

